-- =============================================================================
-- OlivERP · Base schema
-- =============================================================================
-- The runnable source of truth for the database. Load the files in this
-- directory in order; each one is idempotent enough to re-run on a fresh
-- database.
--
--   01-schema.sql     tables, enums, triggers, views   (this file)
--   02-rls.sql        project membership and policies
--   03-agent-api.sql  API keys, idempotency, transactional RPCs
--
-- Everything the application relies on lives here rather than in prose, so the
-- RLS suite (`tests/rls`) can load the real files and ask Postgres itself
-- whether a policy holds. See docs/DATABASE.md for the narrative version.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------
-- Cast explicitly when writing SQL by hand: 'enviada'::estado_venta.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_movimiento') THEN
    CREATE TYPE public.tipo_movimiento AS ENUM (
      'compra', 'venta', 'devolucion_vta', 'ajuste manual', 'devolucion_com'
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_compra') THEN
    CREATE TYPE public.estado_compra AS ENUM ('pendiente', 'recibida', 'cancelada');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_transaccion') THEN
    CREATE TYPE public.tipo_transaccion AS ENUM ('ingreso', 'gasto');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_venta') THEN
    CREATE TYPE public.estado_venta AS ENUM ('pendiente', 'enviada', 'devuelta', 'reembolsada');
  END IF;
END
$$;


-- -----------------------------------------------------------------------------
-- Tables
-- -----------------------------------------------------------------------------
-- `proyectos` is the tenant boundary: every other business table hangs off it,
-- directly or through one join, and that is what the policies in 02-rls.sql are
-- written against.

CREATE TABLE IF NOT EXISTS public.proyectos (
  id     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar     NOT NULL UNIQUE,
  activo boolean     NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.productos (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id integer NOT NULL REFERENCES public.proyectos (id),
  nombre      varchar NOT NULL
);

CREATE INDEX IF NOT EXISTS productos_proyecto_id_idx ON public.productos (proyecto_id);

CREATE TABLE IF NOT EXISTS public.ventas (
  id          integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id integer   NOT NULL REFERENCES public.proyectos (id),
  fecha       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  canal       varchar   NOT NULL,
  estado      public.estado_venta NOT NULL
);

CREATE INDEX IF NOT EXISTS ventas_proyecto_id_idx ON public.ventas (proyecto_id);

-- `proyecto_id` is a copy of the parent sale's. It is redundant by definition,
-- and it is here for the policy in 02-rls.sql: reaching the parent from the
-- policy meant every row scanned ran a subquery against `ventas` — under that
-- table's own policy — and the reporting views scan this table once per
-- product. The column turns that per-row subplan into a column comparison.
-- `derivar_proyecto_venta_detalle` keeps it honest; nothing may set it by hand.
CREATE TABLE IF NOT EXISTS public.venta_detalle (
  id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id              integer NOT NULL REFERENCES public.ventas (id),
  proyecto_id           integer NOT NULL REFERENCES public.proyectos (id),
  producto_id           integer NOT NULL REFERENCES public.productos (id),
  unidades              integer NOT NULL,
  precio_unitario_venta numeric NOT NULL,
  porcentaje_iva        numeric NOT NULL
);

CREATE INDEX IF NOT EXISTS venta_detalle_venta_id_idx ON public.venta_detalle (venta_id);
-- The views aggregate sale lines by product, not by sale.
CREATE INDEX IF NOT EXISTS venta_detalle_producto_id_idx ON public.venta_detalle (producto_id);
CREATE INDEX IF NOT EXISTS venta_detalle_proyecto_id_idx ON public.venta_detalle (proyecto_id);

CREATE TABLE IF NOT EXISTS public.compras (
  id          integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id integer   NOT NULL REFERENCES public.proyectos (id),
  fecha       timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  estado      public.estado_compra NOT NULL
);

CREATE INDEX IF NOT EXISTS compras_proyecto_id_idx ON public.compras (proyecto_id);

-- `proyecto_id` is the parent purchase's, for the same reason as above.
CREATE TABLE IF NOT EXISTS public.compra_detalle (
  id                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compra_id              integer NOT NULL REFERENCES public.compras (id),
  proyecto_id            integer NOT NULL REFERENCES public.proyectos (id),
  producto_id            integer NOT NULL REFERENCES public.productos (id),
  unidades               integer NOT NULL,
  precio_unitario_compra numeric NOT NULL,
  porcentaje_iva         numeric NOT NULL
);

CREATE INDEX IF NOT EXISTS compra_detalle_compra_id_idx ON public.compra_detalle (compra_id);
CREATE INDEX IF NOT EXISTS compra_detalle_producto_id_idx ON public.compra_detalle (producto_id);
CREATE INDEX IF NOT EXISTS compra_detalle_proyecto_id_idx ON public.compra_detalle (proyecto_id);

-- Here `proyecto_id` comes from the product the movement belongs to.
CREATE TABLE IF NOT EXISTS public.movimientos_stock (
  id                     integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id            integer   NOT NULL REFERENCES public.productos (id),
  proyecto_id            integer   NOT NULL REFERENCES public.proyectos (id),
  unidades               integer   NOT NULL,
  tipo_movimiento        public.tipo_movimiento NOT NULL,
  ref_compra_detalle_id  integer   REFERENCES public.compra_detalle (id),
  ref_venta_detalle_id   integer   REFERENCES public.venta_detalle (id),
  fecha                  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS movimientos_stock_producto_id_idx ON public.movimientos_stock (producto_id);
CREATE INDEX IF NOT EXISTS movimientos_stock_proyecto_id_idx ON public.movimientos_stock (proyecto_id);

CREATE TABLE IF NOT EXISTS public.otros_ingresos_gastos (
  id             integer   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id    integer   NOT NULL REFERENCES public.proyectos (id),
  tipo           public.tipo_transaccion NOT NULL,
  concepto       varchar   NOT NULL,
  descripcion    text,
  importe        numeric   NOT NULL,
  porcentaje_iva numeric   DEFAULT NULL,
  fecha          timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS otros_ingresos_gastos_proyecto_id_idx
  ON public.otros_ingresos_gastos (proyecto_id);


-- -----------------------------------------------------------------------------
-- Derived tenant column
-- -----------------------------------------------------------------------------
-- `proyecto_id` on the three child tables is derived, never supplied: the
-- triggers overwrite whatever the caller sent. That is what makes the column
-- safe to write policies against — a client that could choose its own value
-- would be choosing which project's rows it is allowed to write into.
--
-- SECURITY DEFINER so the lookup does not depend on the parent being visible
-- through its own policy; the `WITH CHECK` on the derived value is what decides
-- whether the write is allowed, and it asks exactly the old question: is the
-- caller a member of the project this row lands in?

CREATE OR REPLACE FUNCTION public.derivar_proyecto_venta_detalle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  SELECT v.proyecto_id INTO NEW.proyecto_id
  FROM public.ventas v WHERE v.id = NEW.venta_id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.derivar_proyecto_compra_detalle()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  SELECT c.proyecto_id INTO NEW.proyecto_id
  FROM public.compras c WHERE c.id = NEW.compra_id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.derivar_proyecto_movimiento()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  SELECT p.proyecto_id INTO NEW.proyecto_id
  FROM public.productos p WHERE p.id = NEW.producto_id;
  RETURN NEW;
END;
$$;

-- Trigger plumbing, not API. A trigger function reached over PostgREST only
-- ever errors, but it is exposed there all the same, and the grant arrives on
-- its own: PostgreSQL grants EXECUTE to PUBLIC on every new function and a
-- Supabase project adds `ALTER DEFAULT PRIVILEGES ... TO anon, authenticated`
-- on top, so all three have to be named. Revoking does not stop the triggers —
-- EXECUTE is checked when the trigger is created, not when it fires.
REVOKE EXECUTE ON FUNCTION public.derivar_proyecto_venta_detalle() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.derivar_proyecto_compra_detalle() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.derivar_proyecto_movimiento() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS trg_venta_detalle_proyecto ON public.venta_detalle;
CREATE TRIGGER trg_venta_detalle_proyecto
BEFORE INSERT OR UPDATE ON public.venta_detalle
FOR EACH ROW EXECUTE FUNCTION public.derivar_proyecto_venta_detalle();

DROP TRIGGER IF EXISTS trg_compra_detalle_proyecto ON public.compra_detalle;
CREATE TRIGGER trg_compra_detalle_proyecto
BEFORE INSERT OR UPDATE ON public.compra_detalle
FOR EACH ROW EXECUTE FUNCTION public.derivar_proyecto_compra_detalle();

DROP TRIGGER IF EXISTS trg_movimientos_stock_proyecto ON public.movimientos_stock;
CREATE TRIGGER trg_movimientos_stock_proyecto
BEFORE INSERT OR UPDATE ON public.movimientos_stock
FOR EACH ROW EXECUTE FUNCTION public.derivar_proyecto_movimiento();


-- -----------------------------------------------------------------------------
-- Stock movement triggers
-- -----------------------------------------------------------------------------
-- Stock is never written directly: it is derived from purchase and sale lines,
-- so that a line and its movement cannot disagree. A purchase adds units, a
-- sale removes them.

CREATE OR REPLACE FUNCTION public.sync_movimiento_compra()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO movimientos_stock (producto_id, unidades, tipo_movimiento, ref_compra_detalle_id)
    VALUES (NEW.producto_id, NEW.unidades, 'compra', NEW.id);
  ELSIF (TG_OP = 'UPDATE') THEN
    UPDATE movimientos_stock
    SET unidades = NEW.unidades, producto_id = NEW.producto_id
    WHERE ref_compra_detalle_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.sync_movimiento_venta()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO movimientos_stock (producto_id, unidades, tipo_movimiento, ref_venta_detalle_id)
    VALUES (NEW.producto_id, -NEW.unidades, 'venta', NEW.id);
  ELSIF (TG_OP = 'UPDATE') THEN
    UPDATE movimientos_stock
    SET unidades = -NEW.unidades, producto_id = NEW.producto_id
    WHERE ref_venta_detalle_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_compra_detalle_stock ON public.compra_detalle;
CREATE TRIGGER trg_compra_detalle_stock
AFTER INSERT OR UPDATE ON public.compra_detalle
FOR EACH ROW EXECUTE FUNCTION public.sync_movimiento_compra();

DROP TRIGGER IF EXISTS trg_venta_detalle_stock ON public.venta_detalle;
CREATE TRIGGER trg_venta_detalle_stock
AFTER INSERT OR UPDATE ON public.venta_detalle
FOR EACH ROW EXECUTE FUNCTION public.sync_movimiento_venta();


-- -----------------------------------------------------------------------------
-- Views
-- -----------------------------------------------------------------------------
-- `security_invoker` matters as much as the policies themselves. A view without
-- it runs with its *owner's* privileges, so a reporting view over locked-down
-- tables hands every project's figures to anyone who can select from the view —
-- the policies underneath are simply not consulted.

CREATE OR REPLACE VIEW public.vista_finanzas_diarias
WITH (security_invoker = true) AS
WITH
  ultimo_coste AS (
    SELECT DISTINCT ON (cd.producto_id)
      cd.producto_id,
      cd.precio_unitario_compra AS coste_ultimo_con_iva
    FROM compra_detalle cd
    JOIN compras c ON cd.compra_id = c.id
    ORDER BY cd.producto_id, c.fecha DESC
  ),
  unificado AS (
    SELECT
      v.proyecto_id,
      v.fecha::date AS dia,
      -- Only effective sales count as income; returned and refunded ones do not.
      CASE WHEN v.estado = 'enviada' THEN vd.unidades::numeric * vd.precio_unitario_venta ELSE 0::numeric END AS ingreso_v,
      0::numeric AS gasto_total,
      CASE WHEN v.estado = 'enviada' THEN (vd.unidades::numeric * (vd.precio_unitario_venta - COALESCE(uc.coste_ultimo_con_iva, 0::numeric))) ELSE 0::numeric END AS beneficio_v,
      0::numeric AS gasto_o_base,
      0::numeric AS iva_s,
      -- Prices are VAT-inclusive, so the tax is extracted as rate/(100+rate).
      CASE WHEN v.estado = 'enviada' THEN (vd.unidades::numeric * vd.precio_unitario_venta * (vd.porcentaje_iva / (100::numeric + vd.porcentaje_iva))) ELSE 0::numeric END AS iva_r
    FROM venta_detalle vd
    JOIN ventas v ON vd.venta_id = v.id
    LEFT JOIN ultimo_coste uc ON vd.producto_id = uc.producto_id

    UNION ALL

    SELECT
      c.proyecto_id,
      c.fecha::date AS dia,
      0::numeric AS ingreso_v,
      CASE WHEN c.estado = 'recibida' THEN cd.unidades::numeric * cd.precio_unitario_compra ELSE 0::numeric END AS gasto_total,
      0::numeric AS beneficio_v,
      0::numeric AS gasto_o_base,
      CASE WHEN c.estado = 'recibida' THEN cd.unidades::numeric * cd.precio_unitario_compra * (cd.porcentaje_iva / (100::numeric + cd.porcentaje_iva)) ELSE 0::numeric END AS iva_s,
      0::numeric AS iva_r
    FROM compra_detalle cd
    JOIN compras c ON cd.compra_id = c.id

    UNION ALL

    SELECT
      proyecto_id,
      fecha::date AS dia,
      (CASE WHEN tipo = 'ingreso' THEN importe ELSE 0 END) AS ingreso_v,
      (CASE WHEN tipo = 'gasto' THEN importe ELSE 0 END) AS gasto_total,
      0 AS beneficio_v,
      (CASE WHEN tipo = 'gasto' THEN importe ELSE 0 END) AS gasto_o_base,
      (CASE WHEN tipo = 'gasto' THEN importe * (COALESCE(porcentaje_iva, 0) / (100 + COALESCE(porcentaje_iva, 0))) ELSE 0 END) AS iva_s,
      (CASE WHEN tipo = 'ingreso' THEN importe * (COALESCE(porcentaje_iva, 0) / (100 + COALESCE(porcentaje_iva, 0))) ELSE 0 END) AS iva_r
    FROM otros_ingresos_gastos
  )
SELECT
  u.dia,
  u.proyecto_id,
  p.nombre AS nombre_proyecto,
  sum(u.ingreso_v) AS ingresos,
  sum(u.gasto_total) AS gastos,
  sum(u.ingreso_v) - sum(u.gasto_total) AS balance,
  sum(u.beneficio_v) - sum(u.gasto_o_base) AS urp,
  sum(u.iva_s) AS iva_soportado,
  sum(u.iva_r) AS iva_repercutido,
  sum(u.iva_r) - sum(u.iva_s) AS saldo_iva
FROM unificado u
JOIN proyectos p ON u.proyecto_id = p.id
GROUP BY u.dia, u.proyecto_id, p.nombre;


CREATE OR REPLACE VIEW public.vista_stock_final
WITH (security_invoker = true) AS
WITH
  sub AS (
    SELECT
      p.proyecto_id,
      proy.nombre AS nombre_proyecto,
      p.id AS producto_id,
      p.nombre AS nombre_producto,
      COALESCE((
        SELECT sum(m.unidades) FROM movimientos_stock m WHERE m.producto_id = p.id
      ), 0::bigint) AS stock_actual,
      -- Recent cost first, falling back to the all-time average, then zero.
      COALESCE(
        (SELECT avg(cd.precio_unitario_compra)
           FROM compra_detalle cd
           JOIN compras c ON cd.compra_id = c.id
          WHERE cd.producto_id = p.id AND c.fecha >= (now() - '60 days'::interval)),
        (SELECT avg(cd.precio_unitario_compra)
           FROM compra_detalle cd
          WHERE cd.producto_id = p.id),
        0::numeric
      ) AS coste_ud,
      COALESCE(
        (SELECT avg(vd.precio_unitario_venta)
           FROM venta_detalle vd
           JOIN ventas v ON vd.venta_id = v.id
          WHERE vd.producto_id = p.id AND v.fecha >= (now() - '30 days'::interval)),
        (SELECT avg(vd.precio_unitario_venta)
           FROM venta_detalle vd
          WHERE vd.producto_id = p.id),
        0::numeric
      ) AS venta_ud,
      (SELECT COALESCE(sum(vd.unidades), 0::bigint)
         FROM venta_detalle vd
         JOIN ventas v ON vd.venta_id = v.id
        WHERE vd.producto_id = p.id AND v.fecha >= (now() - '30 days'::interval)
      ) AS num_ventas_30d
    FROM productos p
    JOIN proyectos proy ON p.proyecto_id = proy.id
  )
SELECT
  proyecto_id,
  nombre_proyecto,
  producto_id,
  nombre_producto,
  stock_actual,
  coste_ud,
  venta_ud,
  num_ventas_30d,
  venta_ud - coste_ud AS beneficio_ud,
  (venta_ud - coste_ud) * num_ventas_30d::numeric AS beneficio_total_30d,
  stock_actual::numeric * venta_ud AS valor_stock,
  num_ventas_30d::numeric / 30.0 AS venta_diaria_promedio,
  CASE
    WHEN (num_ventas_30d::numeric / 30.0) > 0::numeric
      THEN stock_actual::numeric / (num_ventas_30d::numeric / 30.0)
    ELSE 999::numeric
  END AS dias_stock_restante
FROM sub;
